site_name: connalysis
repo_url: https://github.com/danielaegassan/connectome_analysis

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - Introduction: 'index.md'
  - 'api_docs.md'
  - Modelling: 'modelling.md'
  - Network: 'network.md'

markdown_extensions:
  - pymdownx.snippets:
      check_paths: true

plugins:
  - search:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_signature_annotations: true
            show_source: true
            show_submodules: true

watch:
  - src/connalysis


